---
# yaml-language-server: $schema=https://raw.githubusercontent.com/HOMES/modules/master/modules/environment-schema.json
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::mafft=7.520
  - conda-forge::pigz=2.8
