---
# yaml-language-server: $schema=https://raw.githubusercontent.com/HOMES/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::clustalo=1.2.4
  - conda-forge::pigz=2.8
